### PR TITLE
Add a list of relevant dependencies

### PR DESCRIPTION
**Pull request by Xyli0**
I have added a list of the main dependencies used in the project to the readme file. Let me know what you think of it.

### CODE REVIEW

**Comment by spiray** [comment]
@Xyli0 Thanks! Can you clone the branch directly and re-submit the PR?

**Comment by Xyli0** [comment]
@spiray for sure.

**Comment by Xyli0** [comment]
@spiray Actually i am not sure how to do this. Could you help?

**Comment by spiray** [comment]
@Xyli0 I sent you an invite to the organization. Firstly, visit this repo and submit a PR with you info added. Then clone the app-backend repo and create a feature branch and push directly to that branch.

**Pull request closed without merging**
