### PR TITLE
Add first draft of RAML design

### PR DESCRIPTION
**Pull request by snordmann**

### CODE REVIEW

**Comment by spiray** [comment]
@sbibow Take a look at how I implemented the response in the contributor controller and make the necessary changes to the sketch.

**Comment by spiray** [comment]
@sbibow 
1. The baseUri should be `https://api.coding.garden`.
2. What is the root endpoint `/contribution-areas` for? Where would that live?

**Comment by snordmann** [comment]
1. Good catch - I will adjust it the next time I work on this
2. It is to query the id to string mapping for the contribution-areas. For the most part it will be enough to use the `included` key on the contributors route, but just for completion's sake it should still exist as route.

---
Speaking about this: How will frontend finally use the data from the backend? Will it have its own mapping from id to icon and string or should the backend provide them?
The id -> string mapping is already on the backend, but mostly to enable API discovery. Should we also include links to the final icons or something like that?

**Comment by spiray** [comment]
@sbibow Should the `/contribution-areas` route be a root endpoint though? It seems excessive to make a separate "module" (routes, controller, tests) all for an endpoint that isn't wholly necessary? It will be far easier/more practical to implement `/contributors/contribution-areas`. 

Regarding the icons, are you referring to the team icons? I would say that should be handled on the frontend but @Sharpie360 and/or @joshuaferr1s may have a better idea.

**Comment by spiray** [comment]
This became irrelevant. I am closing the PR.

**Pull request closed without merging**
