### PR TITLE
[CA-94] History end-point doc

### PR DESCRIPTION
**Pull request by tejas-hosamani**

### CODE REVIEW

**Comment by tejas-hosamani** [comment]
[As a Developer I would like to have the history endpoints documented](https://trello.com/c/cQCVNY45/94-as-a-developer-i-would-like-to-have-the-history-endpoints-documented)

**Comment by spiray** [comment]
@ewenjo I am thinking now that we should just implement the /history/:id route as we already have the handler code in the controller.

**Comment by tejas-hosamani** [comment]
Yup. That would be good. 
Also for /video/:id end point.

**Comment by tejas-hosamani** [comment]
Also, if there is no problem with this PR, I think it's a good idea to merge this before we implement `history/:id`. Because I've another update to make after this. It doesn't make sense to keep this open until that is done. Once those are done, I 'll update the docs and PR them separately. Is that alright?

**Comment by ewenjo** [comment]
Yes, we should do that. @spiray

**Comment by spiray** [comment]
@CodingCreate101 I'd get it out of the way now. All you have to do is add this line to the history.routes.js file
```js
router.get('/:id', getHistory);
```
And then implement a test for it (If you cant do this easily just create a trello card)

**Comment by tejas-hosamani** [comment]
@spiray  Alright. I 'll do it now. What about /video/:id ? It has the base structure ready as well.

**Comment by spiray** [comment]
@CodingCreate101 Yeah, but save that for the PR where you do the Video docs.

**Comment by tejas-hosamani** [comment]
I am actually doing the video doc right now. I wanted to finish off Docs today if possible. I want to get into a bit of DevOps 😬

**Comment by CodingCreate101** [comment]
That's weird. Checks passed on local machine.

**Comment by CodingCreate101** [comment]
Any idea why they are failing?

**Comment by tejas-hosamani** [comment]
Seems like Travis' env has no history with that ID.
~~I'll update the test with something predictable.~~ Nvm. That doesn't work.

**Comment by ewenjo** [comment]
The test database is empty, If you're going to test a history endpoint with a valid ID. You must pre populate the database with test data. Take a look at how we did it in `faq.test.js`

**Comment by tejas-hosamani** [comment]
Yup, I just figured that out. Working on it. :)

**Comment by tejas-hosamani** [comment]
Good Travis.

**Comment by CodingCreate101** [comment]
Can I get a review, please? It's 2 AM. I've another update to make. 😬

**Review by spiray — APPROVED** [review]
Looks good to me

**Review by ewenjo — APPROVED** [review]
lgtm

**Pull request merged**
