### PR TITLE
Changed app.listen message

### PR DESCRIPTION
**Pull request by spiray**
I changed the app.listen message to grant ability to ctrl + click to open the root in browser

### CODE REVIEW

**Review by joshuaferr1s — COMMENTED** [review]
If you are going to do this maybe get the host dynamically too as this will ensure it is always correct no matter where it is run

**Comment by spiray** [comment]
@joshuaferr1s Won't it always be localhost? How would I go about getting the host dynamically? I see the `http` server has a method for that but I don't know if express has it.

**Comment by spiray** [comment]
@joshuaferr1s I made the requested change in the last commit.

**Comment by spiray** [comment]
[Change console output on server start to functional link](https://trello.com/c/Dv7Qu7vo/71-change-console-output-on-server-start-to-functional-link)

**Review by rabbitwerks — APPROVED** [review]
looks good to me

**Review by snordmann — APPROVED** [review]
lgtm

**Pull request merged**
