### PR TITLE
Made all responses uniform and refactored tests

### PR DESCRIPTION
**Pull request by spiray**
I went through all modules and made the responses uniform. THe format is 

```json
[
  {
    "type": "faq",
    "id": "hrt65y8nb",
    "attributes": {
      "question": "How does this work?",
      "answer": "I don't know.",
      "createdAt": "2019-05-20T16:26:05.521Z",
      "updatedAt": "2019-05-20T16:26:05.521Z"
    }
  }
]
```
Please let me know if anything can be formatted more nicely. Should the timestamps be included in the main data or in a nested timestamps object?

### CODE REVIEW

**Comment by spiray** [comment]
[As a Developer, I would like to have less detailed API responses](https://trello.com/c/xQ1h849A/98-as-a-developer-i-would-like-to-have-less-detailed-api-responses)

**Comment by rabbitwerks** [comment]
These changes will be breaking, mobile frontend will need to update their codebase when merged. Looks good to me. Will review fully at home.

**Review by ewenjo — APPROVED** [review]
Lgtm.

**Review by rabbitwerks — COMMENTED** [review]
Do we need the At in createdAt / updatedAt? might be confusing for global context of At/On/En. just my thoughts. 

Code looks good other than that! Nice work and thank you!

**Comment by spiray** [comment]
@Sharpie360 That is the default for the MongoDB timestamps. If you want me to rename them for the response that should be fine but those definitely are a widely used standard as far as I know. Thanks!

**Comment by rabbitwerks** [comment]
@spiray oh gotcha! if thats the case then sounds good to me! just was curious.

**Review by rabbitwerks — APPROVED** [review]

**Pull request merged**
