### PR TITLE
CA-75: Added /contributors/:id route

### PR DESCRIPTION
**Pull request by spiray**
I implemented the /contributors/:id route. I included error handling to throw a comprehensive error if a non-existent ID is requested. Please let me know if you have better ideas for the error message.

### CODE REVIEW

**Comment by spiray** [comment]
[As a Developer, I want to be able to request one contributor by ID](https://trello.com/c/F3BhXzPr/75-as-a-developer-i-want-to-be-able-to-request-one-contributor-by-id)

**Review by ewenjo — APPROVED** [review]
lgtm, should we use different error codes, instead of 500 for everything? For instance, 404 when a contributor is not found.

**Comment by spiray** [comment]
@ewenjo I implemented 404s for non-existent IDs by contributors and FAQs.

**Review by joshuaferr1s — APPROVED** [review]
Looks good to me, nice work.

**Pull request merged**
