### PR TITLE
[CA-107] Build Contributors API Doc - Other Docs are on their way.

### PR DESCRIPTION
**Pull request by tejas-hosamani**
This PR has a lot of "code". It has the base structure (and all the base work) needed for API Doc maintenance. 

So, check whether it's all okay to merge.

### CODE REVIEW

**Comment by tejas-hosamani** [comment]
[As a Developer, I would like to have the Contributors endpoints documented](https://trello.com/c/suX6Gtlk/107-as-a-developer-i-would-like-to-have-the-contributors-endpoints-documented)

**Comment by spiray** [comment]
@CodingCreate101 Thanks! For ease of review we need to have the work done in a branch on this repo. Can you clone this repo (not a fork) and resubmit the PR?

**Comment by ewenjo** [comment]
Also, tests wont pass if you submit a fork

**Comment by tejas-hosamani** [comment]
I don't think I can directly submit to this repo. That's why I forked it. @spiray

**Comment by spiray** [comment]
@CodingCreate101 Ah OK, I just sent you an invite. You should be good to go.

**Pull request closed without merging**
