### PR TITLE
Cron fix

### PR DESCRIPTION
**Pull request by spiray**
This PR includes - 
1. Changed dev start script to automatically seed before starting the server. I was getting errors.
2. I declared the job function separately and called it before the cron scheduler.
3. Only requiring the poll file if the env isn't test.

### CODE REVIEW

**Comment by ewenjo** [comment]
I don't think we should seed the database every time we run the app in development. What kind of errors are you getting?

**Comment by spiray** [comment]
`console.error src/tasks/pollYoutube.js:24
    [cron-job-error] TypeError: Cannot destructure property `date` of 'undefined' or 'null'.`

**Comment by ewenjo** [comment]
Okay, so it cannot find the last date if the database is empty. We should just seed the database once manually before running the app. What do you think?

~~EDIT: Or change the script to work even if the database is empty~~

**Comment by spiray** [comment]
That isn't too hard but what is the downside to reseeding dev databases? It seems more seamless and friendly to new contributors.

**Comment by ewenjo** [comment]
There is no huge downside, but it seems unnecessary. Seeding the database is already in the readme guide, and it shouldn't be too hard to run an extra command.

**Comment by ewenjo** [comment]
I suggest adding something that checks if the database is empty, so that we don't get the error and it doesn't try to seed an empty database using the YouTube API.

**Comment by spiray** [comment]
Ok, I realized the issue is that I am using the same db for test and dev. Ill update and do it manually if necessary.

**Comment by spiray** [comment]
@ewenjo What do you think of this approach in the last commit?

**Comment by ewenjo** [comment]
That works! It will solve the error you're getting.

**Review by ewenjo — DISMISSED** [review]

**Comment by nmigueles** [comment]
> I declared the job function separately and called it before the cron scheduler

Maybe you can declare it in the helper functions as a separate file. Cos this way I could import it in the endpoint to manually fetch the data.

All good from what I saw. Gonna test it at night and leave a proper review😊

**Review by nmigueles — DISMISSED** [review]
Looks nice! Consider what I said in the last comment!

**Review by nmigueles — APPROVED** [review]
Thanks!

**Review by ewenjo — APPROVED** [review]

**Pull request merged**
