### PR TITLE
[CA-95] Docs for /admin endpoint

### PR DESCRIPTION
**Pull request by tejas-hosamani**

### CODE REVIEW

**Comment by tejas-hosamani** [comment]
[As a Developer I would like to have the admin endpoints documented](https://trello.com/c/MaK6UjeT/95-as-a-developer-i-would-like-to-have-the-admin-endpoints-documented)

**Comment by spiray** [comment]
@CodingCreate101 Can you remove the apidocs comments in admin.routes.js?

**Comment by tejas-hosamani** [comment]
I 'll update this PR: https://github.com/CodingGardenCommunity/app-backend/pull/68#issuecomment-523367307
Once this (#69  ) PR goes through. Because both are different types of updates.

@spiray

**Comment by spiray** [comment]
68 will disappear once we merge 69. Just do it on here. GitHub automatically merges a PR if the changes are included in another merged PR.

**Comment by tejas-hosamani** [comment]
Oh.. alright.

**Comment by tejas-hosamani** [comment]
@spiray Yup did that.

**Review by spiray — APPROVED** [review]
Looks good!

**Review by ewenjo — APPROVED** [review]

**Pull request merged**
