### PR TITLE
CA-92: Started adding API Docs for Contributor

### PR DESCRIPTION
**Pull request by spiray**

### CODE REVIEW

**Review by rabbitwerks — APPROVED** [review]

**Comment by rabbitwerks** [comment]
looks good so far

**Comment by spiray** [comment]
This is ready for initial review. @rabbitwerks @ewenjo Can you review it? This is my first attempt @ API docs so please let me know if I did anything wrong.

**Comment by spiray** [comment]
[As a Developer I would like to have the admin endpoints documented](https://trello.com/c/MaK6UjeT/95-as-a-developer-i-would-like-to-have-the-admin-endpoints-documented)

**Comment by spiray** [comment]
[As a Developer I would like to have the contributor endpoints documented](https://trello.com/c/hYqSymHF/92-as-a-developer-i-would-like-to-have-the-contributor-endpoints-documented)

**Review by rabbitwerks — APPROVED** [review]

**Comment by spiray** [comment]
I included the changes in #47.

**Review by ewenjo — APPROVED** [review]
Looks good

**Comment by spiray** [comment]
@w3cj Can you review this when you have a minute? Part of this PR is the prettier feature and I want to get that in as soon as possible. Thanks!

**Comment by jbrundage** [comment]
You should post some screen caps

**Comment by spiray** [comment]
@ewenjo & @rabbitwerks I removed the docs as we don't have anyone as of yet who knows enough about them to approve them and contribute more. I left the doc comments in in case we want to revisit this. This PR now contains the prettier updates. Can you review one more time so I can merge and we can move forward.

**Review by ewenjo — APPROVED** [review]

**Comment by ewenjo** [comment]
Pretty sure we can just merge this already.

**Pull request merged**
