### PR TITLE
Statically serve missing JavaScript files to fix Docs deployment on now.sh

### PR DESCRIPTION
**Pull request by ewenjo**
[Current deployment on now.sh](https://api-dev.coding.garden/docs/v1)
[Test deployment with this fix](https://app-backend.ewenjo.now.sh/docs/v1)

The reason the API docs doesn't work on the dev deployment is because the NPM package `swagger-ui-express` is serving JavaScript files directly from the `node_module/swagger-ui-dist` folder, this should work fine. 

But, when `now.sh` builds the project, NPM packages and most JavaScript files are compressed into fewer files, so a few of the files that used to be served from the `node_module/swagger-ui-dist` folder are now gone and can't be served anymore, which breaks the docs page.

A possible fix for this is to serve the missing JavaScript files statically. This might not be the best solution, but it's a suggestion.

### CODE REVIEW

**Review by spiray — APPROVED** [review]

**Comment by snordmann** [comment]
I don't like having rendered files in my git history. There must be a way to render the files with TravisCI and have them in the deployment, but not in the git history.
Should I investigate this, or do you want to do it?

**Comment by tejas-hosamani** [comment]
I am working on an alternative. I'll let you guys know it goes after a while.

**Comment by ewenjo** [comment]
@sbibow I don't mind having rendered files in my git history, but if you know another way to do it (possibly with Travis), please let me know. Is there anything else you would like to comment on?

**Comment by snordmann** [comment]
Let's wait for @CodingCreate101 to find a solution. After a quick look, I found nothing and would have to allocate more time to this problem. How about we wait until 2019-08-20 to find a solution, and if we couldn't find anything we just merge it as is.

**Comment by tejas-hosamani** [comment]
I am trying this angle here. This doesn't use `swagger-ui-dist` dep. to display the Docs. It uses `.json` or `.yaml` directly. But I am unable to integrate it with our existing file structure.
Here is an example setup I was trying on.
 https://github.com/CodingCreate101/swagger-without-dist

**Comment by tejas-hosamani** [comment]
This is the main setup. If we could somehow integrate it with Doc controller (or router?), it would work without that dep.

```
var fs = require('fs'),
    path = require('path'),
    http = require('http');

var app = require('connect')();
var oas3Tools = require('oas3-tools');
var jsyaml = require('js-yaml');
var serverPort = 8080;

// swaggerRouter configuration
var options = {
  swaggerUi: path.join(__dirname, '/swagger.json'),
  controllers: path.join(__dirname, './controllers'),
  useStubs: process.env.NODE_ENV === 'development' // Conditionally turn on stubs (mock mode)
};

// The Swagger document (require it, build it programmatically, fetch it from a URL, ...)
var spec = fs.readFileSync(path.join(__dirname,'api/swagger.yaml'), 'utf8');
var swaggerDoc = jsyaml.safeLoad(spec);

// Initialize the Swagger middleware
oas3Tools.initializeMiddleware(swaggerDoc, function (middleware) {

  // Interpret Swagger resources and attach metadata to request - must be first in swagger-tools middleware chain
  app.use(middleware.swaggerMetadata());

  // Validate Swagger requests
  app.use(middleware.swaggerValidator());

  // Route validated requests to appropriate controller
  app.use(middleware.swaggerRouter(options));

  // Serve the Swagger documents and Swagger UI
  app.use(middleware.swaggerUi());

  // Start the server
  http.createServer(app).listen(serverPort, function () {
    console.log('Your server is listening on port %d (http://localhost:%d)', serverPort, serverPort);
    console.log('Swagger-ui is available on http://localhost:%d/docs', serverPort);
  });

});

```
This requires additional 3 dependencies though.
connect, 
js-yaml and
oas3-tools

**Review by snordmann — APPROVED** [review]
I think this would bring too much complexity into the project. If it had been an easy fix we should've done that, but it seems that there isn't.

Otherwise this looks good.

**Comment by tejas-hosamani** [comment]
Alright. Yay! We have docs now!

**Pull request merged**
