### PR TITLE
Add basic TravisCI configuration (lint only)

### PR DESCRIPTION
**Pull request by snordmann**

### CODE REVIEW

**Review by spiray — APPROVED** [review]

**Comment by spiray** [comment]
@sbibow Who can approve these? We should get this merged ASAP.

**Comment by snordmann** [comment]
I think everybody that is in the backend team. As long as you have write access to the repo you can create an approving review.

**Comment by spiray** [comment]
I did that but it doesn't seem that it was considered an approved review.

**Review by ewenjo — APPROVED** [review]
Looks good

**Comment by ewenjo** [comment]
> I did that but it doesn't seem that it was considered an approved review.

You do not have write access to this repo, so your review doesn't count toward mergeability.

**Comment by spiray** [comment]
Hmm, I have a merged PR already. Who can change that?

**Review by westborn — APPROVED** [review]
All good, don't kow if I have write access though...Let's see!

**Pull request merged**
