### PR TITLE
[CA-79] :sparkles: contributors routes tested

### PR DESCRIPTION
**Pull request by AkashRajpurohit**
Contributors routes tested

### CODE REVIEW

**Comment by AkashRajpurohit** [comment]
[As a Developer, I would like to have the Contributor endpoints tested](https://trello.com/c/oc4BdOFO/79-as-a-developer-i-would-like-to-have-the-contributor-endpoints-tested)

**Review by spiray — CHANGES_REQUESTED** [review]
@AkashRajpurohit This looks good, can you make sure that you are using 2 space tabs? Can you also test for the response/error body and not just the code?

**Comment by AkashRajpurohit** [comment]
Sure can you let me know if I have to make changes and commit them or it can be directly somehow through github?

**Comment by spiray** [comment]
Make all changes locally and then commit again.

**Comment by AkashRajpurohit** [comment]
Changed the format to two tabs space and testing the response body for both ```/contributors``` and ```/contributors/:id```

**Comment by ewenjo** [comment]
No worries. Code looks good, I'll do a proper review when I get home.

**Review by ewenjo — APPROVED** [review]
lgtm.

**Review by spiray — CHANGES_REQUESTED** [review]
I would destructure `res` where it is declared as we aren't using `res` itself anywhere. Otherwise it looks great!

**Review by spiray — APPROVED** [review]

**Pull request merged**
