### PR TITLE
Editor config

### PR DESCRIPTION
**Pull request by spiray**

### CODE REVIEW

**Comment by ewenjo** [comment]
If using editorconfig is suggested or required, we should probably add some instructions in the README on how to set it up (install plugins etc).

**Comment by spiray** [comment]
@ewenjo @jbrundage Do you think this is important at all? Or should we put this on hold for now?

**Comment by ewenjo** [comment]
It doesn't have to be something we inforce, but I think we should still have it if people want to use it.

**Comment by spiray** [comment]
Ok, can you give an approving review before I merge it?

**Review by ewenjo — APPROVED** [review]

**Pull request merged**
