### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by spiray**

### CODE REVIEW

**Comment by ewenjo** [comment]
Should we finish [this one](https://trello.com/c/SwaEF13l/101-as-a-developer-i-want-a-videos-api-endpoint-that-i-can-use-to-access-cgcj-video-data) before we deploy?

**Comment by spiray** [comment]
Yeah, good idea. I know @rabbitwerks was going to research this. Is [this](https://developers.google.com/youtube/v3/guides/implementation/videos#videos-retrieve-uploads) what we need?

**Comment by ewenjo** [comment]
We already have the fetching logic (`src/helpers/youtubeFetcher.js`). We just need to use the function to fill the database with videos that are not already there, and somehow do this periodically.

**Comment by AndCotOli** [comment]
We should create a Gmail account for the project, and have all the access tokens (for the Youtube API and if we need to use others) in one place

**Comment by ewenjo** [comment]
Good idea, it will be a lot easier to manage API keys that way.

**Comment by AndCotOli** [comment]
LGTM, shall we merge it?

**Review by AndCotOli — DISMISSED** [review]

**Comment by ewenjo** [comment]
No, still waiting for the endpoint to force fetch YouTube videos, and we are going to rename `/faq` and `/video` to `/faqs` and `/videos`

**Comment by AndCotOli** [comment]
Ok, is @NicoMigueles working on it?

**Comment by ewenjo** [comment]
Yes, @NicoMigueles is working on the endpoint and I believe @CodingCreate101 will rename the routes, since the docs has to be updated too.

**Comment by tejas-hosamani** [comment]
Yes. I am updating those. Just to clarify, we are gonna update `video` to `videos` and `faq` to `faqs`, correct?
@ewenjo 

Edit: Oh you already mentioned that, sorry. Didn't see.

**Pull request closed without merging**
