### PR TITLE
Setup initial folder structure, dev env, local db & config

### PR DESCRIPTION
**Pull request by Eckhardt-D**
Folder structure
```
- src
  - index.js
  - config
    - index.js
  - routes
    - index.js
    - home.js
  - middleware
    - index.js
    - example.js
  - database
    - index.js
    - controllers
    - models
```
The idea is that every module gets exported from an index in a role/outcome based folder structure. Which allows for simpler requires.

## Example

```js
const { home, faq, contributors } = require('./routes');

app.use('/', home);
app.use('/faq', faq);
app.use('/contributors', contributors);
```

This is just a suggestion, of course open for discussion.

## Other changes

- Bring in dependencies for configuration/development env.
- Set up base mongo database instance.
- Move connection uri's, server info etc. to config file
- Add cross-env for node_env changes on dev vs. prod
- Remove linebreak-style from eslint rules so we can develop in different environments
- Adhere to 'no-console' rule by applying node process write to console. (Also make it prettier 👍 )
- Set up an example middleware function (logger)

### CODE REVIEW

**Comment by spiray** [comment]
@Eckhardt-D I have 2 questions. 
1) Why is that linbreak rule change necessary? If you run an eslint fix that should take care of it even if your editor has a diff setting.
2) Did you specifically not do a nested destructure on the `require`s?

**Comment by sbibow** [comment]
Please have an expirienced backend developer look over this. I haven't written expressJS code for scale yet, so I am not the best to review this PR.

**Comment by larswaechter** [comment]
Hi, what about grouping routes, controllers and models by modules? So you have something like this:

```
- src
  - index.js
  - config
  - middleware
  - modules
    - user
      - routes.js
      - controller.js
      - model.js
```

**Comment by Eckhardt-D** [comment]
@spiray Thanks Yosef. Yes I intentionally did not nest the de structuring, I don't think it's semantic. But if nested de structuring is a requirement I'm fine with adapting. As for the lint rule `--fix` was not working, neither was using built in lint tool in Vs Code, also obviously not just doing `enter` on windows either. Is this rule of great importance? If so I'll just find a workaround or use my Macbook or Ubuntu system for contribution on this.

Else we could look into docs:

screenshot from 2019-03-04 21-21-08

The two options are `unix` and `windows`. Let me know what you think.

**Comment by Eckhardt-D** [comment]
@larswaechter Yes, I was on the fence about this modular approach compared to the large list of files and I agree. Let's have a discussion and I can always re-implement when we have the actual modules laid out. Was just trying to get the ball rolling here :)

**Comment by Eckhardt-D** [comment]
@larswaechter I would also rather modularize the test suites close to their targets (when we have them), either as a single file or a folder to avoid confusion.

**Comment by spiray** [comment]
@Eckhardt-D No requirements, I was just wondering. We can discuss the line-break issue at our next meeting. Are you on the discord server?

**Comment by Eckhardt-D** [comment]
@spiray Yes I am. We can do that. Will then update the PR when we have a common-ground :+1:

**Comment by westborn** [comment]
@Eckhardt-D @larswaechter I'd like to be part of the discussion on this too...I prefer the module based appraoch but, not committed either way.
I'll check the discord for times.

**Comment by rabbitwerks** [comment]
as far as the linebreak, ive also run into this issue of not being able to change it unless i click the bottom right tab on VS code that you can toggle between crlf or just lf. 
Lets chat more in the backend channel to include as many team devs as possible :)

**Comment by w3cj** [comment]
We decided to use the module folder format in the last backend meeting.

Each module folder has:

* moduleName.controller.js
* moduleName.model.js
* moduleName.routes.js
* moduleName.test.js

**Comment by Eckhardt-D** [comment]
Alright, I’ll adjust accordingly thanks.

**Comment by Eckhardt-D** [comment]
Adjusted folder structure to spec in the meeting

**Comment by Eckhardt-D** [comment]
[Backend: structure and configure application to initialize development environment.](https://trello.com/c/9jNGSSlj/56-backend-structure-and-configure-application-to-initialize-development-environment)

**Review by ewenjo — APPROVED** [review]
Looks good!

**Review by spiray — APPROVED** [review]

**Comment by spiray** [comment]
I have still not been given write access. I am waiting for the second review as well :(

**Review by rabbitwerks — CHANGES_REQUESTED** [review]
We are using yarn package manager and as such all packages should be installed using it. Please replace any npm installed packages with yarn installed ones.

**Comment by Eckhardt-D** [comment]
@Sharpie360 Hi Sean, Change request complete 💯

**Review by rabbitwerks — APPROVED** [review]
corrected package installation successful! can set up project with `yarn` command. approving this PR. nice work!

**Pull request merged**
