### PR TITLE
Updated /faq to /faqs and /video to /videos

### PR DESCRIPTION
**Pull request by tejas-hosamani**
~~**Please merge this after actual endpoint update.** Docs on these two ends points do not work as of now.~~

### CODE REVIEW

**Comment by tejas-hosamani** [comment]
Seems like something's wrong with yarn.lock file.
When I installed packages for the first time, I had used npm instead of yarn. That has messed things up for sure.

If I just use the yarn lock file that we have on dev branch at the moment, would that be enough? @spiray @ewenjo

**Comment by spiray** [comment]
Can you make the change in the routes.js file as well? Yeah, just delete you package-lock.json and run yarn install.

**Comment by ewenjo** [comment]
Rename files and folders as well and don’t forget to update the tests

**Comment by tejas-hosamani** [comment]
About the yarn, I did try that. but yarn says it's up to date.

**Comment by tejas-hosamani** [comment]
**In progress.**
Could you please review these updates until I make further updates to actual endpoints? @ewenjo @spiray

**Comment by ewenjo** [comment]
Looks good at first glance, will do a proper review once you're finished

**Comment by tejas-hosamani** [comment]
@ewenjo @spiray Please review these changes.

**Comment by spiray** [comment]
We still have some inconsistencies with FAQ vs. FAQs. Can you do some final searches and make sure all are covered?

**Comment by tejas-hosamani** [comment]
Oh sure, I'll do that.

In some instances, I've left them on purpose for example, Schema, it's a Schema of just faq.

Also in case of addFAQ and removeFAQ. Because those are actions on just one single FAQ.
..etc.

This was my reasoning in my head. Please clarify whether I should change them all to faqs instead, for consistency.

**Comment by spiray** [comment]
@CodingCreate101 I made a minor change. I think this is good to go!

**Review by spiray — DISMISSED** [review]
Looks great!

**Review by ewenjo — DISMISSED** [review]
lgtm!

**Pull request merged**
