### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by spiray**
I added 4 badges per the approval of some backend members in Discord. They are -

1. Package.json repo version.
2. Dependencies status.
3. Contributors count.
4. Commit activity by a per month metric. (This can be changed)

I also installed Husky and added `yarn run lint` to the pre-commit script so as to avoid linting errors at the PR level.

Thanks and please respond with any questions!

### CODE REVIEW

**Review by ewenjo — APPROVED** [review]
Looks good.

**Review by rabbitwerks — CHANGES_REQUESTED** [review]
please add a new line at the end of package.json, other than that looks alright. need to run locally

**Comment by rabbitwerks** [comment]
> Looks good.

did you get to run it locally?

**Comment by spiray** [comment]
VSCode is not letting me :( working on figuring this out. Why do we need the newline? Can I add the .vscode/ folder to the .gitignore?

**Comment by ewenjo** [comment]
> > Looks good.
> 
> did you get to run it locally?

Yes, I did. Everything worked fine and it passed with the current linter script.

**Comment by spiray** [comment]
Ok, @Sharpie360 It should be clean now.

**Review by rabbitwerks — APPROVED** [review]
Looks good.

**Pull request merged**
