### PR TITLE
Docker setup 🐳

### PR DESCRIPTION
**Pull request by tejas-hosamani**

### CODE REVIEW

**Comment by snordmann** [comment]
Shouldn't the env for the containers be set in the docker-compose file?

**Comment by tejas-hosamani** [comment]
Yes, you are absolutely right. I 'll update it first thing in the morning!

**Comment by snordmann** [comment]
Could you please also add a documentation on how to run the development environment in the README.md? Otherwise I don't see any problem to merge this. Good work 👍

**Comment by tejas-hosamani** [comment]
Yes, I ll. I had planned to do so after having proper Docker setup. I have another minor update to make and then I'll have the README.md file updated.

And thank you for your kind encouragement. 🙂

**Comment by tejas-hosamani** [comment]
I might have to set up this whole thing again and submit new PR. I don't even remember what I did so far. I 'll just leave this PR for ref for now.

**Comment by spiray** [comment]
@CodingCreate101 Should this be closed? Or do you want to wait until #87 is merged?

**Comment by tejas-hosamani** [comment]
I'd like to wait until the other one is merged if that's okay. I'd like to have this a reference, yet.

**Comment by tejas-hosamani** [comment]
Closing the PR. Please keep the branch, though.

**Pull request closed without merging**
