### PR TITLE
Added contributors route

### PR DESCRIPTION
**Pull request by spiray**
One of the items that @w3cj mentioned were part of the MVP was getting the contributors data from the GitHub repository. I added the GET route to the main index file. Once the folder/file structure is established this will obviously be moved. I am also aware that this route doesnt implement the proper versioning and JSON:API format yet. Thanks!

### CODE REVIEW

**Comment by ewenjo** [comment]
Routes should be in separate files. Keep the main file clean.

Look at the folder structure we currently [have ](https://github.com/CodingGardenCommunity/app-backend/pull/10#issuecomment-470285942)

**Comment by spiray** [comment]
@ewenjo That file structure wasn't implemented or merged to develop yet... Once it is there I will move it to the right file. How would I go about implementing it for contributors? 
`src`  
    `Contributor`
      `contributor.routes.js`?

**Comment by ewenjo** [comment]
Yes, of course. But I would wait until we have added the folder structure, so we can deal with error handling, using the right format etc. Meanwhile we can keep the PR open and merge it when we get that far. Also, have we decided to use _node-fetch_ as the http-client?

**Comment by ewenjo** [comment]
> @ewenjo That file structure wasn't implemented or merged to develop yet... Once it is there I will move it to the right file. How would I go about implementing it for contributors?
> `src`
> `Contributor`
> `contributor.routes.js`?

Yeah, that looks right.

**Comment by spiray** [comment]
Ok, @Eckhardt-D Are you working on updating your PR? 
I don't know if there was a discussion about which package to use but I have found node-fetch to be really good and also has the benefit of being nearly identical to the browser Fetch API.
I will work on implementing that structure now.

**Comment by spiray** [comment]
@ewenjo @Sharpie360 See latest commit.

**Review by rabbitwerks — CHANGES_REQUESTED** [review]
re-reviewing, old comment, nvm this

**Review by rabbitwerks — COMMENTED** [review]
waiting for updated PR from @Eckhardt-D before approval, looks good so far. will need to be rebased into updated CA-56 branch most likely.

**Comment by spiray** [comment]
@ewenjo @Sharpie360  @w3cj Can you guys review my latest commit (implemented contrib route with **_`new`_** file structure)? I started clean after #10 was merged. What do you think of the way I setup the controller and the route? Should I delete the model file for contributors as we are getting the data directly from GitHub and not from a DB?

**Review by ewenjo — APPROVED** [review]
Linter passed, code is well structured. Json Api response and rate limiting must be impleneted in the future to protect this endpoint.

**Review by joshuaferr1s — APPROVED** [review]
All looks good to me. Good job! ✨

**Review by rabbitwerks — APPROVED** [review]

**Pull request merged**
